// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2RrxpRFKKy2a84jaUo--8BAD1X1_mY8k',
    appId: '1:891594229541:web:eb029ce5e521f59a97fccc',
    messagingSenderId: '891594229541',
    projectId: 'scar-fbdf6',
    authDomain: 'scar-fbdf6.firebaseapp.com',
    storageBucket: 'scar-fbdf6.appspot.com',
    measurementId: 'G-PEKHD1PZ35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJDaiLa-bn3flZAJeQ9QJFCA_vN4lFVc',
    appId: '1:891594229541:android:a7bfbb5afcca47c497fccc',
    messagingSenderId: '891594229541',
    projectId: 'scar-fbdf6',
    storageBucket: 'scar-fbdf6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4CqhXYPZzRhnNWxbNWZEVzBfJp1db0-Q',
    appId: '1:891594229541:ios:fe091d76df97105e97fccc',
    messagingSenderId: '891594229541',
    projectId: 'scar-fbdf6',
    storageBucket: 'scar-fbdf6.appspot.com',
    iosBundleId: 'com.example.scar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4CqhXYPZzRhnNWxbNWZEVzBfJp1db0-Q',
    appId: '1:891594229541:ios:fe091d76df97105e97fccc',
    messagingSenderId: '891594229541',
    projectId: 'scar-fbdf6',
    storageBucket: 'scar-fbdf6.appspot.com',
    iosBundleId: 'com.example.scar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2RrxpRFKKy2a84jaUo--8BAD1X1_mY8k',
    appId: '1:891594229541:web:88d5335549965bb897fccc',
    messagingSenderId: '891594229541',
    projectId: 'scar-fbdf6',
    authDomain: 'scar-fbdf6.firebaseapp.com',
    storageBucket: 'scar-fbdf6.appspot.com',
    measurementId: 'G-TNHVP5FY2E',
  );
}
